import React, { useState } from 'react';
import { Loader2, Plus, Trash2, Upload, Pencil } from 'lucide-react';
import { useTransactions } from '../../hooks/useTransactions';
import { Card, CardContent } from '../../components/common/Card/Card';
import { Button } from '../../components/common/Button/Button';
import { Modal } from '../../components/common/Modal/Modal';
import { Input } from '../../components/common/Input/Input';
import { formatCurrency } from '../../utils/currency';
import { formatDate } from '../../utils/date';
import { handleApiError } from '../../services/api/axios';

export const TransactionsPage: React.FC = () => {
  const { transactions, isLoading, isError, error, refetch, createTransaction, isCreating, updateTransaction, isUpdating, deleteTransaction, isDeleting, importCSV, isImporting } = useTransactions();
  const [modal, setModal] = useState<'create' | 'edit' | 'import' | null>(null);
  const [editingId, setEditingId] = useState<string | null>(null); const [description, setDescription] = useState(''); const [amount, setAmount] = useState(''); const [file, setFile] = useState<File | null>(null); const [actionError, setActionError] = useState('');
  const save = async (e: React.FormEvent) => { e.preventDefault(); setActionError(''); try { if (editingId) await updateTransaction({ id: editingId, description, amount: Number(amount) }); else await createTransaction({ description, amount: Number(amount), type: 'EXPENSE', category: 'Outros', date: '', status: 'COMPLETED', paymentMethod: 'PIX' }); setDescription(''); setAmount(''); setEditingId(null); setModal(null); } catch (err) { setActionError(handleApiError(err).message); } };
  const openCreate = () => { setEditingId(null); setDescription(''); setAmount(''); setModal('create'); };
  const openEdit = (id: string, currentDescription: string, currentAmount: number) => { setEditingId(id); setDescription(currentDescription); setAmount(String(currentAmount)); setModal('edit'); };
  const upload = async (e: React.FormEvent) => { e.preventDefault(); if (!file) return setActionError('Selecione um arquivo CSV para importar.'); setActionError(''); try { await importCSV(await file.text()); setModal(null); setFile(null); } catch (err) { setActionError(handleApiError(err).message); } };
  const remove = async (id: string) => { if (!window.confirm('Deseja excluir esta transação?')) return; try { await deleteTransaction(id); } catch (err) { setActionError(handleApiError(err).message); } };
  if (isLoading) return <div className="flex justify-center p-12"><Loader2 className="animate-spin text-blue-600" /></div>;
  if (isError) return <div className="rounded-xl bg-rose-50 border border-rose-300 p-4 text-rose-700">{handleApiError(error).message}<button className="ml-2 underline" onClick={() => refetch()}>Tentar novamente</button></div>;
  return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-slate-900 dark:text-white">Transações</h1><p className="text-sm text-slate-500">Listagem e operações disponíveis no sistema.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => setModal('import')} leftIcon={<Upload className="w-4 h-4" />}>Importar CSV</Button><Button onClick={openCreate} leftIcon={<Plus className="w-4 h-4" />}>Nova</Button></div></div>{actionError && <div className="rounded-xl bg-rose-50 border border-rose-300 p-3 text-sm text-rose-700">{actionError}</div>}
    <Card><CardContent className="p-0">{transactions.length === 0 ? <div className="p-12 text-center text-slate-500">Nenhuma transação cadastrada ainda.</div> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b text-left text-slate-500"><tr><th className="p-4">Descrição</th><th className="p-4">Categoria</th><th className="p-4">Valor</th><th className="p-4">Criada em</th><th className="p-4" /></tr></thead><tbody>{transactions.map(tx => <tr key={tx.id} className="border-b border-slate-100 dark:border-slate-800"><td className="p-4 font-medium">{tx.description}</td><td className="p-4">{tx.category}</td><td className="p-4">{formatCurrency(tx.amount)}</td><td className="p-4">{formatDate(tx.date)}</td><td className="p-4 flex gap-3"><button onClick={() => openEdit(tx.id, tx.description, tx.amount)} className="text-blue-600"><Pencil className="w-4 h-4" /></button><button disabled={isDeleting} onClick={() => remove(tx.id)} className="text-rose-600"><Trash2 className="w-4 h-4" /></button></td></tr>)}</tbody></table></div>}</CardContent></Card>
    <Modal isOpen={modal === 'create' || modal === 'edit'} onClose={() => setModal(null)} title={editingId ? 'Editar transação' : 'Nova transação'} description="A API aceita descrição e valor; a categoria é definida pelo processamento do backend."><form className="space-y-4" onSubmit={save}><Input label="Descrição" required value={description} onChange={e => setDescription(e.target.value)} /><Input label="Valor" required type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} /><Button type="submit" isLoading={isCreating || isUpdating}>Salvar</Button></form></Modal>
    <Modal isOpen={modal === 'import'} onClose={() => setModal(null)} title="Importar CSV" description="Envie um CSV com as colunas exigidas pelo backend."><form className="space-y-4" onSubmit={upload}><input type="file" accept=".csv,text/csv" onChange={e => setFile(e.target.files?.[0] ?? null)} /><p className="text-xs text-slate-500">Formato esperado: descricao,valor</p><Button type="submit" isLoading={isImporting}>Importar</Button></form></Modal>
  </div>;
};
