spring:
  application:
    name: finance
  datasource:
    # Ajustado: Adicionado &allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/finance_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: Y2hhdmVfc2VjcmV0YV9tdWl0b19ncmFuZGVfcGFyYV9vX2hhY2thdGhvbl9zZWd1cmFuY2E=
  expiration: 86400000 # 24 horas

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    # Ajustado: Adicionado &allowPublicKeyRetrieval=true para quando rodar dentro do container
    url: jdbc:mysql://mysql:3306/finance_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root